#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
import os

# Mandatory variables
top = '.'
out = 'build'

def options(opt):
    autowaf.set_options(opt)

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            gui.cc
            launchkey_mk3.cc
            launchkey_mk3_midi.cc
            launchkey_mk3_ports.cc
            launchkey_mk3_interface.cc
            rangecontrollableset.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_launchkey_mk3"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = [ '.', './launchkey_mk3']
    obj.name         = 'libardour_launchkey_mk3'
    obj.target       = 'ardour_launchkey_mk3'
    obj.uselib       = 'GTKMM GTK GDK XML OSX'
    obj.use          = 'libardour libardour_cp libardour_midisurface libgtkmm2ext libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

def shutdown():
    autowaf.shutdown()
